package rag

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Ownera1/pi-rag-go/internal/store"
)

func TestLegacyVoyageAliasAndEndpointFingerprint(t *testing.T) {
	root := t.TempDir()
	registry := `{"version":1,"providers":{"proxy-voyage":{"type":"voyage","baseUrl":"https://proxy.example/v1","auth":{"type":"bearer","env":"PROXY_KEY"},"models":{"embedding":{"voyage-4-lite":{"dimensions":1024}}}}}}`
	if err := os.WriteFile(filepath.Join(root, "provider.json"), []byte(registry), 0600); err != nil {
		t.Fatal(err)
	}
	cfg, contract, err := legacyProvider(root, "proxy-voyage", "voyage-4-lite", 1024)
	if err != nil || cfg.Type != "voyage" || cfg.APIKeyEnv != "PROXY_KEY" || contract != "ae4d45e8e8e87007" {
		t.Fatalf("provider=%+v contract=%s err=%v", cfg, contract, err)
	}
	// The expected digest above was generated by the TypeScript JSON.stringify
	// property order followed by SHA-256, independent of this Go implementation.
	if _, _, err := legacyProvider(root, "missing", "voyage-4-lite", 1024); err == nil {
		t.Fatal("unregistered provider accepted")
	}
}

func TestLegacyVectorContractRejectsChangedEndpoint(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	legacyConfig := `{"embedding":{"provider":"proxy-voyage","model":"voyage-4-lite","dimensions":2}}`
	registry := `{"version":1,"providers":{"proxy-voyage":{"type":"voyage","baseUrl":"https://proxy.example/v1","auth":{"type":"bearer","env":"PROXY_KEY"},"models":{"embedding":{"voyage-4-lite":{"dimensions":2}}}}}}`
	for name, value := range map[string]string{"config.json": legacyConfig, "provider.json": registry} {
		if err := os.WriteFile(filepath.Join(root, name), []byte(value), 0600); err != nil {
			t.Fatal(err)
		}
	}
	_, contract, err := legacyProvider(root, "proxy-voyage", "voyage-4-lite", 2)
	if err != nil {
		t.Fatal(err)
	}
	db, err := store.Open(filepath.Join(root, "rag.db"), false, 2)
	if err != nil {
		t.Fatal(err)
	}
	fp := `{"provider":"proxy-voyage","model":"voyage-4-lite","dimensions":2,"providerContract":"` + contract + `","contract":"l2-unit-v1"}`
	if err := db.SetMetadata(ctx, "embedding_fingerprint", fp); err != nil {
		t.Fatal(err)
	}
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}
	core, err := Open(Options{StoreDir: root, LegacyReadOnly: true, Embedder: fakeEmbedding{}})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := core.Query(ctx, "evidence", QueryOptions{Mode: "hybrid"}); err != nil {
		t.Fatal(err)
	}
	core.Close()
	changed := strings.Replace(registry, "https://proxy.example/v1", "https://other.example/v1", 1)
	if err := os.WriteFile(filepath.Join(root, "provider.json"), []byte(changed), 0600); err != nil {
		t.Fatal(err)
	}
	core, err = Open(Options{StoreDir: root, LegacyReadOnly: true, Embedder: fakeEmbedding{}})
	if err != nil {
		t.Fatal(err)
	}
	defer core.Close()
	if _, err := core.Query(ctx, "evidence", QueryOptions{Mode: "hybrid"}); err == nil || !strings.Contains(err.Error(), "contract") {
		t.Fatalf("changed endpoint should reject hybrid: %v", err)
	}
	if _, err := core.Query(ctx, "evidence", QueryOptions{Mode: "bm25"}); err != nil {
		t.Fatalf("BM25 should remain available: %v", err)
	}
}
